# see https://github.com/notFloran/mjml-bundle#binary
mjml:
    renderer: 'binary'
    options:
        binary: '%kernel.project_dir%/node_modules/.bin/mjml'
        node: null # default: null
#        node: '/home3/shoppkc0/.nvm/versions/node/v14.17.0/bin/node' # default:
        minify: true # default: false
        validation_level: skip
